const VENDOR_LEADS=[
  {
    "countryGroup": "Myanmar / Burma",
    "name": "Tet Nay Lin Co., Ltd. / Hair Supplier Myanmar / Myanmar Hair Exporter",
    "city": "Yangon",
    "area": "North Okkalapa",
    "contact": "+959441433143",
    "secondaryContact": "+959775145650",
    "whatsappUrl": "https://wa.me/959441433143",
    "secondaryWhatsappUrl": "https://wa.me/959775145650",
    "email": "",
    "website": "",
    "sourceUrl": "https://www.myanmarhairextension.com/contact.html",
    "sourceUrl2": "https://myanmarhairexporter.com/contact-us-send-inquiry/",
    "quality": "High",
    "type": "Factory/exporter",
    "products": "Burmese virgin/remy hair, wigs, closures/frontals, weft, bulk",
    "address": "No.10/11, Khwar Nyo 7th St, Hta Qtr, North Okkalapa Township, Yangon",
    "riskNotes": "Direct website lists WhatsApp + address; likely same network as Myanmar Hair Exporter. Ask for DICA extract if using business visa invitation."
  },
  {
    "countryGroup": "Myanmar / Burma",
    "name": "Hair Myanmar Extension / Hair Extension Myanmar",
    "city": "Yangon",
    "area": "North Okkalapa",
    "contact": "+95973165461",
    "secondaryContact": "+959791254063",
    "whatsappUrl": "https://wa.me/95973165461",
    "secondaryWhatsappUrl": "https://wa.me/959791254063",
    "email": "",
    "website": "",
    "sourceUrl": "https://www.myanmarhairextension.com/",
    "sourceUrl2": "",
    "quality": "Medium-High",
    "type": "Supplier/collector/manufacturer",
    "products": "Hair from salons, donation centers, monasteries, direct ponytail cutting, sub-collectors",
    "address": "No.11, Khwar Nyo St, Htawunbe Quarter, North Okkala Township/Mingalardon, Yangon",
    "riskNotes": "Good sourcing-language fit for raw hair collection; verify whether same/related to Tet Nay Lin."
  },
  {
    "countryGroup": "Myanmar / Burma",
    "name": "Burmese Hair Extensions Center 1 / BHC",
    "city": "Yangon",
    "area": "North Okkalapa",
    "contact": "+959797290256",
    "secondaryContact": "",
    "whatsappUrl": "https://wa.me/959797290256",
    "secondaryWhatsappUrl": "",
    "email": "",
    "website": "",
    "sourceUrl": "https://www.beautynailhairsalons.com/MM/Yangon/768994363255832/Burmese-Hair-Extensions-Center-1",
    "sourceUrl2": "https://www.findglocal.com/MM/Yangon/768994363255832/Burmese-Hair-Extensions-Center-1",
    "quality": "High",
    "type": "Supplier/processor",
    "products": "Virgin hair, non-remy hair, raw hair, washing/drying prep; recent 2026 posts",
    "address": "No.305, Myittar Street, North Okkalapa, Yangon 11031",
    "riskNotes": "Recent public posts list WhatsApp and claim no chemical/no mixed/no lice. Good first Yangon visit."
  },
  {
    "countryGroup": "Myanmar / Burma",
    "name": "Efficient Hair Company / BHC-linked site",
    "city": "Yangon",
    "area": "North Okkalapa",
    "contact": "+959797290256",
    "secondaryContact": "",
    "whatsappUrl": "https://wa.me/959797290256",
    "secondaryWhatsappUrl": "",
    "email": "",
    "website": "",
    "sourceUrl": "http://www.efficienthairbusiness.com/",
    "sourceUrl2": "https://www.beautynailhairsalons.com/MM/Yangon/768994363255832/Burmese-Hair-Extensions-Center-1",
    "quality": "Medium",
    "type": "Website/contact lead",
    "products": "Likely linked to Burmese Hair Extensions Center listing",
    "address": "North Okkalapa, Yangon",
    "riskNotes": "Website appears attached to BHC listing; verify active site/contact before visiting."
  },
  {
    "countryGroup": "Myanmar / Burma",
    "name": "Deok San",
    "city": "Yangon",
    "area": "Hlaing Tharyar",
    "contact": "",
    "secondaryContact": "",
    "whatsappUrl": "",
    "secondaryWhatsappUrl": "",
    "email": "",
    "website": "",
    "sourceUrl": "https://www.findglocal.com/MM/Yangon/154494-8/genre/181550638549454/Hairpieces%2B%26%2BExtensions",
    "sourceUrl2": "",
    "quality": "Medium",
    "type": "Factory/manufacturer lead",
    "products": "Hairpieces/extensions; industrial zone listing",
    "address": "No.274, Shwe Yin Aye Kyaung Street, Hlaing Tharyar Industrial Zone 5, Yangon",
    "riskNotes": "No WhatsApp found in public scrape; good physical visit lead only after local driver/assistant confirms."
  },
  {
    "countryGroup": "Myanmar / Burma",
    "name": "Win Aate Group Co., Ltd.",
    "city": "Yangon",
    "area": "Hlaing Tharyar",
    "contact": "",
    "secondaryContact": "",
    "whatsappUrl": "",
    "secondaryWhatsappUrl": "",
    "email": "",
    "website": "",
    "sourceUrl": "https://www.yangondirectory.com/listing/freelisting/wigs",
    "sourceUrl2": "",
    "quality": "Medium",
    "type": "Wig/factory lead",
    "products": "Wigs/hairpieces",
    "address": "315 Tine Tar Min Gyi St, Shwe Linban Industrial Zone, Hlaing Tharyar Township",
    "riskNotes": "Listed under wigs; confirm whether manufacturing, trading, or retail."
  },
  {
    "countryGroup": "Myanmar / Burma",
    "name": "DICA-listed virgin Remy / wig factory lead",
    "city": "Yangon",
    "area": "South Dagon / Dagon Seikkan",
    "contact": "",
    "secondaryContact": "",
    "whatsappUrl": "",
    "secondaryWhatsappUrl": "",
    "email": "",
    "website": "",
    "sourceUrl": "https://www.dica.gov.mm/",
    "sourceUrl2": "",
    "quality": "Medium",
    "type": "Industrial/factory lead",
    "products": "Virgin Remy double-drawn hair and wigs",
    "address": "South Dagon / Dagon Seikkan area, Yangon",
    "riskNotes": "Official investment/industrial source mentioned hair/wig production in this zone; use as target area for local broker search, not a direct appointment."
  },
  {
    "countryGroup": "Myanmar / Burma",
    "name": "Sandar Burmese Hair",
    "city": "Yangon",
    "area": "Yangon general",
    "contact": "",
    "secondaryContact": "",
    "whatsappUrl": "",
    "secondaryWhatsappUrl": "",
    "email": "",
    "website": "",
    "sourceUrl": "https://glahair.com/blog/burmese-hair-factory/",
    "sourceUrl2": "",
    "quality": "Low-Medium",
    "type": "Factory/supplier lead",
    "products": "Wefts, bulk hair, tape-ins, tips, clips, reported as Burmese hair factory",
    "address": "Yangon, Myanmar",
    "riskNotes": "Secondary-source lead; need current phone/social verification before relying on it."
  },
  {
    "countryGroup": "Cambodia",
    "name": "Cambodian Hair Factory",
    "city": "Phnom Penh / Vietnam-linked",
    "area": "",
    "contact": "+84855555901",
    "secondaryContact": "",
    "whatsappUrl": "https://wa.me/84855555901",
    "secondaryWhatsappUrl": "",
    "email": "",
    "website": "",
    "sourceUrl": "https://cambodianhairfactory.com/contact-page/",
    "sourceUrl2": "https://cambodianhairfactory.com/about-us/",
    "quality": "Medium",
    "type": "Brand/vendor; says products mainly from Vietnamese factories",
    "products": "Wholesale human hair, extensions; source appears Vietnam despite Cambodia branding",
    "address": "",
    "riskNotes": "Useful contact, but not true Cambodian-origin by their own site; categorize as Vietnam-source vendor."
  },
  {
    "countryGroup": "Cambodia",
    "name": "Virgin Hair Cambodia",
    "city": "Cambodia / UK contact",
    "area": "",
    "contact": "+447930554652",
    "secondaryContact": "",
    "whatsappUrl": "https://wa.me/447930554652",
    "secondaryWhatsappUrl": "",
    "email": "",
    "website": "",
    "sourceUrl": "https://www.virginhaircambodia.com/",
    "sourceUrl2": "https://www.virginhaircambodia.com/contact",
    "quality": "High",
    "type": "Ethical Cambodian hair manufacturer/supplier",
    "products": "Sheitels, wigs, human hair; collection teams in rural villages",
    "address": "Cambodia; exact factory address not public",
    "riskNotes": "Strong ethical sourcing language; phone is UK number, request Cambodia factory visit details and collection proof."
  },
  {
    "countryGroup": "Cambodia",
    "name": "Cambodian Raw Hair - CRH",
    "city": "Siem Reap",
    "area": "",
    "contact": "+855966823098",
    "secondaryContact": "",
    "whatsappUrl": "https://wa.me/855966823098",
    "secondaryWhatsappUrl": "",
    "email": "",
    "website": "",
    "sourceUrl": "https://www.findglocal.com/KH/Siem-Reap/115186696796611/Cambodian-Raw-Hair---CRH",
    "sourceUrl2": "https://www.cambodianrawhair.com/",
    "quality": "Medium-High",
    "type": "Premium hair company / collector",
    "products": "Raw Cambodian hair, closures, frontals, collected from donors",
    "address": "Kantrok Village, Svay Dangkum, Siem Reap",
    "riskNotes": "Public listing says created in 2020 and collects hair from donor; WhatsApp not explicitly guaranteed but mobile likely reachable."
  },
  {
    "countryGroup": "Cambodia",
    "name": "Cambodian Raw Hair Extensions",
    "city": "USA/Cambodia",
    "area": "",
    "contact": "+85570835626",
    "secondaryContact": "",
    "whatsappUrl": "https://wa.me/85570835626",
    "secondaryWhatsappUrl": "",
    "email": "",
    "website": "",
    "sourceUrl": "https://www.cambodianrawhairextensions.com/contactus",
    "sourceUrl2": "",
    "quality": "Medium-High",
    "type": "Retail/wholesale brand",
    "products": "Cambodian raw hair extensions; explicitly asks wholesalers to use WhatsApp",
    "address": "Mailing address USA; Cambodia sources not public",
    "riskNotes": "Has direct phone/WhatsApp and scam warning; ask for exact Cambodia collection/factory proof."
  },
  {
    "countryGroup": "Cambodia",
    "name": "Sambo Hair Extensions",
    "city": "Phnom Penh",
    "area": "",
    "contact": "+85512421922",
    "secondaryContact": "",
    "whatsappUrl": "https://wa.me/85512421922",
    "secondaryWhatsappUrl": "",
    "email": "",
    "website": "",
    "sourceUrl": "https://www.beautynailhairsalons.com/KH/Phnom-Penh/1435048319854511/Sambo-hair-extensions",
    "sourceUrl2": "",
    "quality": "Medium",
    "type": "Supplier",
    "products": "Cambodian virgin hair, raw hair, wefted hair, bulk hair",
    "address": "No.137, Street 06, Kontoak, Porsenchey, Borey New World 1, Phnom Penh",
    "riskNotes": "Active-ish listing with phone; verify wholesale capacity and export experience."
  },
  {
    "countryGroup": "Cambodia",
    "name": "Apsarangkor Premium Virgin Hair",
    "city": "Siem Reap",
    "area": "",
    "contact": "",
    "secondaryContact": "",
    "whatsappUrl": "",
    "secondaryWhatsappUrl": "",
    "email": "",
    "website": "",
    "sourceUrl": "https://www.beautynailhairsalons.com/KH/Siem-Reap/299889944285394/Apsarangkor-Premium-Virgin-Hair",
    "sourceUrl2": "",
    "quality": "Medium",
    "type": "Manufacturer/supplier lead",
    "products": "Premium virgin hair; claims raw hair from donors; bundles, closure/frontal, wig",
    "address": "Thlok Angdoung Village, Sangkat Sla Kram, Siem Reap",
    "riskNotes": "No public WhatsApp found; use Facebook/Instagram route and local visit if in Siem Reap."
  },
  {
    "countryGroup": "Cambodia",
    "name": "Beon Hair Extensions",
    "city": "Siem Reap / USA",
    "area": "",
    "contact": "",
    "secondaryContact": "",
    "whatsappUrl": "",
    "secondaryWhatsappUrl": "",
    "email": "",
    "website": "",
    "sourceUrl": "https://www.findglocal.com/KH/Siem-Reap/107401070838366/Beon-Hair-Extensions",
    "sourceUrl2": "",
    "quality": "Low-Medium",
    "type": "Supplier/provider",
    "products": "Virgin Cambodian hair, wigs, closures, frontals, bundles, ponytails",
    "address": "8RHR+F5 Krong, Siem Reap",
    "riskNotes": "Older activity; email/social DM may work. Verify before spending time."
  },
  {
    "countryGroup": "Cambodia",
    "name": "KeiSa International Ltd.",
    "city": "Phnom Penh",
    "area": "",
    "contact": "",
    "secondaryContact": "",
    "whatsappUrl": "",
    "secondaryWhatsappUrl": "",
    "email": "",
    "website": "",
    "sourceUrl": "https://kh56490.contact.page/",
    "sourceUrl2": "",
    "quality": "Low-Medium",
    "type": "Hair/extensions and beauty supplier",
    "products": "Cambodian virgin hair extensions, bulk hair, sewing hair",
    "address": "No.8D, Sorla (St.371), Trea 1 Village, Phnom Penh",
    "riskNotes": "Directory hides exact phone/email; use business directory/contact form or local lookup."
  },
  {
    "countryGroup": "Cambodia",
    "name": "The Elect Cambodian Hair Company",
    "city": "Phnom Penh",
    "area": "",
    "contact": "",
    "secondaryContact": "",
    "whatsappUrl": "",
    "secondaryWhatsappUrl": "",
    "email": "",
    "website": "",
    "sourceUrl": "https://www.beautynailhairsalons.com/KH/Phnom-Penh/179503428841451/The-Elect-Cambodian-Hair-Company",
    "sourceUrl2": "",
    "quality": "Low-Medium",
    "type": "Raw Cambodian hair company lead",
    "products": "Raw Cambodian hair extensions; donor-sourced claims",
    "address": "Phnom Penh, Cambodia",
    "riskNotes": "Listing has recent crawl but limited direct contact; verify website/social."
  },
  {
    "countryGroup": "Cambodia",
    "name": "Dellahs Hair",
    "city": "Cambodia / UK contact",
    "area": "",
    "contact": "+447367693170",
    "secondaryContact": "",
    "whatsappUrl": "https://wa.me/447367693170",
    "secondaryWhatsappUrl": "",
    "email": "",
    "website": "",
    "sourceUrl": "https://dellahshair.tumblr.com/",
    "sourceUrl2": "",
    "quality": "Medium",
    "type": "Brand/factory claim",
    "products": "Raw Cambodian and Burmese hair; claims factory in Cambodia",
    "address": "Cambodia factory, exact address not public",
    "riskNotes": "Public Tumblr lists WhatsApp for wholesale only; verify factory address and live tour."
  },
  {
    "countryGroup": "Vietnam",
    "name": "T&T Vietnam Hair",
    "city": "Bac Ninh",
    "area": "",
    "contact": "+84983830188",
    "secondaryContact": "+84974011202",
    "whatsappUrl": "https://wa.me/84983830188",
    "secondaryWhatsappUrl": "https://wa.me/84974011202",
    "email": "",
    "website": "",
    "sourceUrl": "https://ttvietnamhair.com/",
    "sourceUrl2": "",
    "quality": "High",
    "type": "Factory/direct supplier",
    "products": "Wigs, bundles, extensions, weft, bulk, closures/frontals, tape-ins, clips, ponytails",
    "address": "Bac Ninh, Vietnam",
    "riskNotes": "Multiple WhatsApp numbers and factory-direct language; good first contact."
  },
  {
    "countryGroup": "Vietnam",
    "name": "Lyn Hair Factory",
    "city": "Hanoi / Bac Ninh",
    "area": "",
    "contact": "+84936085069",
    "secondaryContact": "",
    "whatsappUrl": "https://wa.me/84936085069",
    "secondaryWhatsappUrl": "",
    "email": "",
    "website": "",
    "sourceUrl": "https://lynhair.com/human-hair-extensions/",
    "sourceUrl2": "",
    "quality": "High",
    "type": "Factory/supplier",
    "products": "Vietnamese bundles, wigs, remy, virgin hair",
    "address": "Office: My Dinh Plaza, 138 Tran Binh St, Nam Tu Liem, Hanoi",
    "riskNotes": "Direct website lists WhatsApp and office."
  },
  {
    "countryGroup": "Vietnam",
    "name": "AZYHAIR",
    "city": "Bac Ninh",
    "area": "",
    "contact": "+84896638986",
    "secondaryContact": "",
    "whatsappUrl": "https://wa.me/84896638986",
    "secondaryWhatsappUrl": "",
    "email": "",
    "website": "",
    "sourceUrl": "https://azyhair.com/",
    "sourceUrl2": "",
    "quality": "High",
    "type": "Factory/supplier",
    "products": "Raw human hair, bulk hair, custom wigs, private label",
    "address": "Bai Thuong, Hiep Hoa, Bac Ninh, Vietnam",
    "riskNotes": "Current site, WhatsApp, factory location, B2B claims."
  },
  {
    "countryGroup": "Vietnam",
    "name": "Van Anh Hair",
    "city": "Bac Ninh / Hanoi",
    "area": "",
    "contact": "+84586888388",
    "secondaryContact": "+84915501994",
    "whatsappUrl": "https://wa.me/84586888388",
    "secondaryWhatsappUrl": "https://wa.me/84915501994",
    "email": "",
    "website": "",
    "sourceUrl": "https://vananhhair.com/contact/",
    "sourceUrl2": "",
    "quality": "High",
    "type": "Factory/supplier",
    "products": "Raw hair, virgin hair, high-quality extensions",
    "address": "Dong Xuat, Dong Tho, Yen Phong, Bac Ninh",
    "riskNotes": "Direct contact page lists staff WhatsApp links; also Ruby +84 368 563 592."
  },
  {
    "countryGroup": "Vietnam",
    "name": "Luxshine Hair Factory",
    "city": "Vietnam",
    "area": "",
    "contact": "+84986483797",
    "secondaryContact": "",
    "whatsappUrl": "https://wa.me/84986483797",
    "secondaryWhatsappUrl": "",
    "email": "",
    "website": "",
    "sourceUrl": "https://www.beautynailhairsalons.com/VN/Unknown/181859389029354/Luxshine-Hair-Factory--Wholesale-Hair-Extensions",
    "sourceUrl2": "https://luxshinehair.com",
    "quality": "High",
    "type": "Factory/wholesale extensions",
    "products": "Vietnamese human hair, machine weft, wigs, custom hair",
    "address": "Vietnam; exact factory not in listing",
    "riskNotes": "Recent listing and WhatsApp. Ask for factory address before visit."
  },
  {
    "countryGroup": "Vietnam",
    "name": "Govihair",
    "city": "Bac Ninh",
    "area": "",
    "contact": "+84934832698",
    "secondaryContact": "",
    "whatsappUrl": "https://wa.me/84934832698",
    "secondaryWhatsappUrl": "",
    "email": "",
    "website": "",
    "sourceUrl": "https://govihair.com/",
    "sourceUrl2": "",
    "quality": "High",
    "type": "Wholesale factory",
    "products": "Raw Vietnamese hair, single donor, private label",
    "address": "Vietnam; factory details on site",
    "riskNotes": "Site lists WhatsApp and B2B support."
  },
  {
    "countryGroup": "Vietnam",
    "name": "RUSA Hair",
    "city": "Hanoi / Vinh Phuc",
    "area": "",
    "contact": "+84836855468",
    "secondaryContact": "",
    "whatsappUrl": "https://wa.me/84836855468",
    "secondaryWhatsappUrl": "",
    "email": "",
    "website": "",
    "sourceUrl": "https://www.rusahair.com/",
    "sourceUrl2": "",
    "quality": "High",
    "type": "Factory/supplier",
    "products": "Keratin, tape-in, weft, raw material, clip-in, OEM/ODM",
    "address": "Office: 1A, 137 My Dinh St, Tu Liem, Hanoi; factory: Trung Nguyen Commune, Yen Lac, Vinh Phuc",
    "riskNotes": "Direct site lists office, factory and WhatsApp."
  },
  {
    "countryGroup": "Vietnam",
    "name": "Hairac Vietnam",
    "city": "Bac Ninh / Hanoi",
    "area": "",
    "contact": "+84904650468",
    "secondaryContact": "",
    "whatsappUrl": "https://wa.me/84904650468",
    "secondaryWhatsappUrl": "",
    "email": "",
    "website": "",
    "sourceUrl": "https://hairac.com.vn/",
    "sourceUrl2": "",
    "quality": "High",
    "type": "Factory/supplier",
    "products": "Bulk raw hair, colored bulk, keratin, tape, clip, weft, hair systems",
    "address": "Factory: Bai Thuong Village, Hiep Hoa Commune, Bac Ninh; office: Ngoai Giao Doan, Xuan Dinh, Hanoi",
    "riskNotes": "Direct site lists factory, office, WhatsApp and email."
  },
  {
    "countryGroup": "Vietnam",
    "name": "APOHAIR",
    "city": "Vietnam",
    "area": "",
    "contact": "+84862132366",
    "secondaryContact": "",
    "whatsappUrl": "https://wa.me/84862132366",
    "secondaryWhatsappUrl": "",
    "email": "",
    "website": "",
    "sourceUrl": "https://apohair.com/",
    "sourceUrl2": "https://apohair.com/raw-vietnamese-hair-wholesale/",
    "quality": "High",
    "type": "Factory-direct manufacturer",
    "products": "Raw Vietnamese hair, extensions, wigs, bundles, bulk; MOQ 200g",
    "address": "Vietnam; exact factory address not in snippet",
    "riskNotes": "Direct site lists 24/7 WhatsApp and factory-direct manufacturer language."
  },
  {
    "countryGroup": "Vietnam",
    "name": "GREATHAIR Vietnam",
    "city": "Vietnam",
    "area": "",
    "contact": "+84813282399",
    "secondaryContact": "",
    "whatsappUrl": "https://wa.me/84813282399",
    "secondaryWhatsappUrl": "",
    "email": "",
    "website": "",
    "sourceUrl": "https://greathair.com.vn/",
    "sourceUrl2": "",
    "quality": "Medium-High",
    "type": "Factory/supplier",
    "products": "Raw Vietnamese hair, OEM/ODM extensions",
    "address": "Vietnam",
    "riskNotes": "Direct site lists phone and WhatsApp button; request exact factory address."
  },
  {
    "countryGroup": "Vietnam",
    "name": "K-Hair",
    "city": "Bac Ninh / Hanoi",
    "area": "",
    "contact": "",
    "secondaryContact": "",
    "whatsappUrl": "",
    "secondaryWhatsappUrl": "",
    "email": "",
    "website": "",
    "sourceUrl": "https://k-hair.com/",
    "sourceUrl2": "",
    "quality": "Medium-High",
    "type": "Direct manufacturer",
    "products": "Raw Vietnamese human hair; 2,000 m² facility in Bac Ninh; 2 tons/month claim",
    "address": "Bac Ninh facility; Hanoi/online sales",
    "riskNotes": "Strong factory claims but WhatsApp number not captured in search snippet; use site chat/quote form."
  },
  {
    "countryGroup": "Vietnam",
    "name": "VQ Hair Factory",
    "city": "Bac Ninh / Hanoi",
    "area": "",
    "contact": "+84962318090",
    "secondaryContact": "",
    "whatsappUrl": "https://wa.me/84962318090",
    "secondaryWhatsappUrl": "",
    "email": "",
    "website": "",
    "sourceUrl": "https://vqhair.com/about-us/",
    "sourceUrl2": "https://vqhair.com/",
    "quality": "High",
    "type": "Wholesale factory",
    "products": "Bundles, closures/frontals, raw Vietnamese hair, extensions and wigs",
    "address": "Factory: Dong Bich village, Dong Tho commune, Yen Phong district, Bac Ninh; office: Nam Tu Liem, Hanoi",
    "riskNotes": "Direct site lists factory address and WhatsApp."
  },
  {
    "countryGroup": "Vietnam",
    "name": "Nice Hair Vietnam",
    "city": "Bac Ninh / Hanoi",
    "area": "",
    "contact": "+84967670678",
    "secondaryContact": "",
    "whatsappUrl": "https://wa.me/84967670678",
    "secondaryWhatsappUrl": "",
    "email": "",
    "website": "",
    "sourceUrl": "https://nicehairvn.com/",
    "sourceUrl2": "",
    "quality": "High",
    "type": "Factory",
    "products": "Weft, bulk, closure/frontal, wigs, tape, color hair",
    "address": "Factory: Dong Tho Commune, Yen Phong District, Bac Ninh; office/warehouse: 181 Xuan Thuy, Cau Giay, Hanoi",
    "riskNotes": "Direct site lists factory and hotline; verify WhatsApp before sending money."
  },
  {
    "countryGroup": "Vietnam",
    "name": "Mic Hair",
    "city": "Hanoi",
    "area": "",
    "contact": "+84962279910",
    "secondaryContact": "+84968167955",
    "whatsappUrl": "https://wa.me/84962279910",
    "secondaryWhatsappUrl": "https://wa.me/84968167955",
    "email": "",
    "website": "",
    "sourceUrl": "https://michair.vn/contact",
    "sourceUrl2": "https://www.beautynailhairsalons.com/VN/Hanoi/595724573902434/MIC-Hair-Nhung",
    "quality": "High",
    "type": "Supplier/company",
    "products": "Natural raw hair, wefts, extensions, frontals",
    "address": "Hanoi City / Nam Tu Liem, Hanoi",
    "riskNotes": "Direct contact page lists WhatsApp/phone; listing also has staff WhatsApp."
  },
  {
    "countryGroup": "Vietnam",
    "name": "Macsara Hair",
    "city": "Hanoi",
    "area": "",
    "contact": "+84986980492",
    "secondaryContact": "",
    "whatsappUrl": "https://wa.me/84986980492",
    "secondaryWhatsappUrl": "",
    "email": "",
    "website": "",
    "sourceUrl": "https://glahair.com/blog/raw-vietnamese-hair-vendors/",
    "sourceUrl2": "https://macsara.vn/",
    "quality": "Medium",
    "type": "Factory/vendor",
    "products": "Weft, clip-in, tape-in, tip-in, wigs",
    "address": "3A Building, Lane 82 Duy Tan St, Dich Vong Hau Ward, Cau Giay, Hanoi",
    "riskNotes": "Secondary source lists WhatsApp and address; verify directly via official site before buying."
  },
  {
    "countryGroup": "Vietnam",
    "name": "NiceHairs.vn / Nice Hairs family supplier",
    "city": "Bac Ninh",
    "area": "",
    "contact": "+84983203668",
    "secondaryContact": "+84985115168",
    "whatsappUrl": "https://wa.me/84983203668",
    "secondaryWhatsappUrl": "https://wa.me/84985115168",
    "email": "",
    "website": "",
    "sourceUrl": "https://nicehairs.com/About",
    "sourceUrl2": "",
    "quality": "Medium-High",
    "type": "Supplier/factory",
    "products": "Single drawn, double drawn, machine wefted hair",
    "address": "Trung Ban, Dong Tho Commune, Yen Phong District, Bac Ninh",
    "riskNotes": "Direct site lists two WhatsApp numbers and capacity; older-looking site, verify current operations."
  }
];
const SOURCING_RESEARCH={
  "lastUpdated": "2026-08-17",
  "sourceWorkbook": "SE_Asia_Hair_Factory_Sourcing_Yangon_Cambodia_Vietnam.xlsx",
  "safety": [
    {
      "topic": "U.S. government safety advisory",
      "finding": "The U.S. State Department lists Burma/Myanmar as Level 4: Do Not Travel due to armed conflict, unrest, arbitrary law enforcement, poor health infrastructure, landmines/UXO and crime.",
      "recommendation": "If you go anyway, keep it Yangon-only, use private driver/security-minded local fixer, avoid protests/crowds, do not do overland sourcing runs without a current local security check.",
      "sourceUrl": "https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/burma-travel-advisory.html"
    },
    {
      "topic": "Tourist eVisa basics",
      "finding": "Tourist eVisa requires passport validity of at least 6 months, recent color photo, passport bio page, return ticket proof, and hotel/registered accommodation proof.",
      "recommendation": "Good fit only if the trip is genuinely tourism plus informal meetings; for factory purchasing meetings, business visa may be safer/cleaner.",
      "sourceUrl": "https://evisa.moip.gov.mm/apply-visa/notice-tourist-visa"
    },
    {
      "topic": "Business eVisa basics",
      "finding": "Business eVisa requires invitation by a registered Myanmar company/chamber and company documents including registration/DICA extract/annual return proof.",
      "recommendation": "Ask a preferred supplier to send proper invitation docs only after you verify the company is active and legitimate.",
      "sourceUrl": "https://evisa.moip.gov.mm/apply-visa/notice-business-visa"
    },
    {
      "topic": "eVisa ports",
      "finding": "Current eVisa entry ports include Yangon International Airport, Mandalay, Nay Pyi Taw, and Kawthaung land border.",
      "recommendation": "For this trip, use Yangon International Airport only; do not build a multi-city route until security is checked city-by-city.",
      "sourceUrl": "https://evisa.moip.gov.mm/notice/tourist"
    },
    {
      "topic": "Yangon factory geography",
      "finding": "The best concentration of direct hair leads found is North Okkalapa; secondary leads are Hlaing Tharyar and South Dagon/Dagon Seikkan.",
      "recommendation": "Day 1: North Okkalapa appointments only. Day 2: backup/revisits. Day 3: only if local driver confirms Hlaing Tharyar/South Dagon route is safe that week.",
      "sourceUrl": "https://www.myanmarhairextension.com/contact.html"
    },
    {
      "topic": "Go / no-go rule",
      "finding": "Do not rely only on an online listing for a Myanmar visit.",
      "recommendation": "Require: confirmed appointment, live video call from facility, hotel/driver confirmation, supplier sends pin, no demand for large deposit, and route check on the same day.",
      "sourceUrl": "Compiled from official advisory + sourcing workflow"
    }
  ],
  "scripts": [
    {
      "useCase": "First supplier message",
      "message": "Hi, my name is Rocky. I own Hair Maiden India in the USA. I am looking for a direct factory/collector for raw human hair and finished products. Can you send me your wholesale price list, product catalog, and a short live video of your factory or stock today? I am especially interested in raw ponytail/bulk hair, wefted hair, closures/frontals, and wigs."
    },
    {
      "useCase": "Myanmar/Yangon verification",
      "message": "Before I travel to Yangon, can you please confirm your full address, send a Google Maps pin, and show me on video where the hair is washed, sorted, wefted, and packed? Also, is the hair collected in Myanmar, or imported from India/Bangladesh/Pakistan and processed in Myanmar?"
    },
    {
      "useCase": "Cambodia verification",
      "message": "I am looking for real Cambodian-origin hair, not Vietnamese hair sold under a Cambodian name. Can you explain where your hair is collected, whether it is single donor or mixed donor, and whether I can visit your Cambodia collection/factory location?"
    },
    {
      "useCase": "Vietnam verification",
      "message": "I am comparing Vietnamese hair factories for long-term wholesale. Can you send pricing by kg for raw bulk, machine weft, tape-ins, closures/frontals, and wigs? Also please confirm MOQ, sample policy, DHL/FedEx shipping cost to Los Angeles, and whether you offer private label packaging."
    },
    {
      "useCase": "Factory visit request",
      "message": "I may be visiting soon. Are you open to a buyer visiting your facility? I would like to see raw hair stock, sorting, washing, wefting, ventilation/wig-making if available, and packing/export process. Please let me know the best date/time and what documents you need from me."
    },
    {
      "useCase": "Sample order terms",
      "message": "For a first test order, I want to start with a small paid sample, then scale if quality is consistent. Please quote: 100g raw bulk, 3 bundles 18/20/22, 5x5 closure, 13x4 frontal, and one wig sample. Please include shipping time, payment options, and return/exchange policy."
    }
  ],
  "strategy": [
    {
      "country": "Myanmar/Yangon",
      "bestUse": "Raw Burmese-origin verification and niche sourcing",
      "why": "Potential differentiation if you can prove true Burmese donor origin; Yangon has direct public leads.",
      "risk": "Safety/advisory risk; business visa documentation; some Myanmar processors may import hair from other countries.",
      "nextAction": "Do WhatsApp/video verification first; only visit North Okkalapa appointments in person."
    },
    {
      "country": "Cambodia",
      "bestUse": "Premium raw Cambodian-origin sourcing, small batch/story-driven product",
      "why": "Cambodian hair can be marketed as rare/premium if origin and ethics are documented.",
      "risk": "Many “Cambodian” vendors are actually Vietnam-source; fewer transparent factory addresses.",
      "nextAction": "Prioritize VHC, CRH, Cambodian Raw Hair Extensions; ask for donor/collection proof."
    },
    {
      "country": "Vietnam",
      "bestUse": "Scalable manufacturing, private label, extensions/wigs/OEM",
      "why": "Largest and most organized factory ecosystem among the three; many WhatsApp-ready suppliers.",
      "risk": "More competition; some “raw/single donor” claims need verification.",
      "nextAction": "Contact 8-12 suppliers, request catalogs/samples, then shortlist 3 factories around Bac Ninh/Hanoi."
    }
  ]
};
